apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    # Puerto REST
    - name: http
      port: 6000
      targetPort: 6000
      protocol: TCP
    # Puerto gRPC
    - name: grpc
      port: 50055
      targetPort: 50055
      protocol: TCP
  type: ClusterIP
